name: Deploy

on:
  push:
    branches:
      - beta
      - main

jobs:
  deploy-beta:
    if: github.ref == 'refs/heads/beta'
    runs-on: [self-hosted, actions-runner-sped]

    steps:
      - name: Deploy BETA
        run: |

          cd /var/www/html/betasped

          git fetch origin
          git reset --hard origin/beta

          sudo chown -R user_planeacion:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache

          composer install --no-dev --optimize-autoloader

          php artisan migrate --force || true

          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear

          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          php artisan storage:link
          php artisan route:clear

          mkdir -p storage/framework/views
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, actions-runner-sped]

    steps:
      - name: Deploy PRODUCCION
        run: |

          cd /var/www/html/sped

          git fetch origin
          git reset --hard origin/main
          sudo chown -R user_planeacion:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache
          sudo chmod -R g+s storage bootstrap/cache

          composer install --no-dev --optimize-autoloader

          php artisan migrate --force || true

          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear

          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          php artisan storage:link
          php artisan route:clear